# -*- coding: utf-8 -*-
"""SCRAPPING.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fbk5TsygVyf8ikZscolnRYiiafWKtjgW
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.imobiliariaeuropa.com.br/imoveis/para-alugar" 
response = requests.get(url)

soup = BeautifulSoup(response.content, 'html.parser')

myInfoArray = []

links = soup.select('a.slide-home-btn')

for link in links:
    pushHref = link['href']
    newResponse = requests.get(pushHref)
    newSoup = BeautifulSoup(newResponse.content, 'html.parser')
    title = newSoup.select_one('h1.elementor-heading-title').get_text()
    value = newSoup.select_one('h2.elementor-heading-title').get_text(strip=True) 
    description = newSoup.select('div.elementor-text-editor p')[2].get_text()
    area = newSoup.select('div.col-6')[-1].text.split()[0] + newSoup.select('div.col-6')[-1].text.split()[2]

    if value != 'Sob Consulta':
        value += ",00"

    aux = [title.split()[0], value, area.strip(), description]
    myInfoArray.append(aux)

df = pd.DataFrame(myInfoArray, columns=['Título', 'Aluguel', 'Área', 'Descrição'])

df.to_excel('scrapImobiliaria.xlsx', index=False)
df.to_csv('scrapImobiliaria.csv', index=False)